name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Set up Postgres
      uses: CasperWA/postgresql-action@v1
      with:
        postgresql version: '14'
        postgresql db: 'db'
        postgresql user: admin
        postgresql password: admin

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Cache yarn
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      working-directory: ./WordUnveil
      run: yarn install --immutable

    - name: Run Build
      working-directory: WordUnveil
      run: yarn rw build

    - name: Run Lint
      working-directory: WordUnveil
      run: yarn rw lint

    - name: Run Diagnostics
      working-directory: WordUnveil
      run: yarn rw check

    - name: Run Tests
      working-directory: WordUnveil
      run: yarn rw test
      env:
        TEST_DATABASE_URL: postgresql://admin:admin@localhost:5432/db

    - name: Run tests with coverage
      working-directory: WordUnveil
      run: yarn rw test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        fail_ci_if_error: true
